In [8]:
import tweepy
import jsonlines
import pandas as pd

consumer_key = "EPpD21VPkhxzz7lvv2K7M1rUL"
consumer_secret = "5KB6BXznGDnlC4nzsF8gb4T4r6x0xMcgpIo2J4ECuI6ZczRzeQ"
access_token = "1114884355711746054-Fz4BdRWnQjR8x4Rf8DzAOr6Wkl90ru"
access_token_secret = "IWmC1JWUAhsMu6LGPpkpffphmuwcVv9FVlQfAvghoGuin"

# Creating the authentication object
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
# Setting your access token and secret
auth.set_access_token(access_token, access_token_secret)
# Creating the API object while passing in auth information
api = tweepy.API(auth) 

# The Twitter user who we want to get tweets from
name = "midasIIITD"
# Number of tweets to pull
tweetCount = 20

# Calling the user_timeline function with our parameters
results = api.user_timeline(id=name, count=tweetCount)

with jsonlines.open("results.jsonl",mode='w') as writer:
    for tweet in results:
        writer.write(tweet._json)

answer=[]

with jsonlines.open("results.jsonl",mode='r') as reader:
    for item in reader.iter():
        temp=[]
        temp.append(item['text'])
        temp.append(item['created_at'][:16])
        temp.append(item['favorite_count'])
        temp.append(item['retweet_count'])
        answer.append(temp)

df=pd.DataFrame(answer,columns=['Tweet Text','Date Created','Likes','Retweets'])

In [9]:
df

,Tweet Text,Date Created,Likes,Retweets
0,"@himanchalchandr Meanwhile, complete CV/NLP ta...",Sun Apr 07 14:17,0,0
1,@sayangdipto123 Submit as per the guideline ag...,Sun Apr 07 14:17,0,0
2,We request all students whose interview are sc...,Sun Apr 07 11:43,0,1
3,"Other queries: ""none of the Tweeter Apis give ...",Sun Apr 07 06:55,3,2
4,"Other queries: ""do we have to make two differe...",Sun Apr 07 06:53,4,1
5,"Other queries: ""If using Twitter api, it does ...",Sun Apr 07 05:32,4,1
6,Response to some queries asked by students on ...,Sun Apr 07 05:29,6,1
7,RT @kdnuggets: Top 8 #Free Must-Read #Books on...,Sat Apr 06 17:11,0,2
8,@nupur_baghel @PennDATS Congratulation @nupur_...,Sat Apr 06 16:43,17,3
9,We have emailed the task details to all candid...,Fri Apr 05 16:08,10,1
10,RT @rfpvjr: Our NAACL paper on polarization in...,Fri Apr 05 04:05,0,16
11,RT @kdnuggets: Effective Transfer Learning For...,Fri Apr 05 04:04,0,11
12,RT @stanfordnlp: What’s new in @Stanford CS224...,Wed Apr 03 18:31,0,59
13,RT @DeepMindAI: Today we're releasing a large-...,Wed Apr 03 17:04,0,848
14,RT @ylecun: Congratulations Jitendra Malik !\n...,Wed Apr 03 09:03,0,16
15,RT @IIITDelhi: Another chance to take admissio...,Wed Apr 03 07:46,0,4
16,Dear @midasIIITD internship candidates who hav...,Tue Apr 02 04:20,8,1
17,Looking forward to your paper submission to @I...,Tue Apr 02 02:44,5,1
18,RT @ngrams: Reproducibility in multimedia rese...,Tue Apr 02 02:35,0,7
19,Online application for https://t.co/DJFDrQsHZP...,Mon Apr 01 06:53,7,2